name: Mask synced secret values
on:
  workflow_dispatch
jobs:
  synced-secret-examples:
    runs-on: ubuntu-latest
    steps:
      - name: ✓ Granularity secret-key
        run: |
          echo '${{ secrets.VAULT_KV_13A66AFB_MY_SECRET_FOO }}'

      # - name: ✓ Mask synced secret values
      #   run: |
      #     for v in $(echo '${{ secrets.VAULT_KV_13A66AFB_MY_SECRET_FOO }}' | jq -r '.[]'); do
      #       echo "::add-mask::$v"
      #     done
