name: Read secrets sync values
on:
  workflow_dispatch
jobs:
  synced-secret-examples:
    runs-on: ubuntu-latest
    steps:
      - name: ✓ Granularity secret-key
        run: |
          echo '${{ secrets.VAULT_ADMIN_TENANT_1_SECRET_DATABASE_DEV_API_KEY }}'

      - name: ✓ Granularity secret-path
        run: |
          echo '${{ secrets.VAULT_ADMIN_TENANT_1_SECRET_DATABASE_DEV }}'

      - name: ✓ Granularity secret-key Mask synced secret values
        run: |
          for v in $(echo '${{ secrets.VAULT_ADMIN_TENANT_1_SECRET_DATABASE_DEV }}' | jq -r '.[]'); do
            echo "::add-mask::$v"
          done
